export const CHANG_INPUT_VALUE = 'change_input_value'
export const DELETE_LIST = 'delete_list'
export const ADD_LIST = 'add_list'
export const INIT_LIST = 'init_list'
export const GET_INIT_LIST = 'get_init_list'